In [5]:
# 練習 10-1
# 範例 5x5 灰階圖
import cv2
import numpy as np

image = np.array([
    [0, 1, 0, 1, 0],
    [0, 1, 1, 1, 0],
    [1, 1, 1, 1, 0],
    [0, 1, 1, 1, 1],
    [0, 0, 1, 0, 1]
], dtype=np.float32)

# Sobel 核心
Gx = np.array([
    [-1, 0, 1],
    [-2, 0, 2],
    [-1, 0, 1]
], dtype=np.float32)

Gy = np.array([
    [-1, -2, -1],
    [ 0,  0,  0],
    [ 1,  2,  1]
], dtype=np.float32)

# 使用 OpenCV 的 copyMakeBorder 增加邊界
padded_image = cv2.copyMakeBorder(image, 1, 1, 1, 1, cv2.BORDER_REFLECT101)

# 輔助函數:卷積
def convolve2d(image, kernel):
    height, width = image.shape
    k = kernel.shape[0]
    offset = k // 2
    
    # 初始化輸出圖
    output = np.zeros((height - 2 * offset, width - 2 * offset), dtype=np.float32)
    
    for i in range(offset, height - offset):
        for j in range(offset, width - offset):
            region = image[i - offset:i + offset + 1, j - offset:j + offset + 1]
            output[i - offset, j - offset] = np.sum(region * kernel)
    return output

# 計算 Gx、Gy
grad_x = convolve2d(padded_image, Gx)
grad_y = convolve2d(padded_image, Gy)

# 計算梯度幅值
gradient = np.abs(grad_x) + np.abs(grad_y)

# 印出結果
for row in gradient:
    print(row.astype(int))


[0 2 0 2 0]
[2 4 2 4 0]
[0 2 0 4 2]
[4 6 2 2 0]
[0 4 0 0 0]


In [ ]:
# 練習10-2 Sobel – real case 1
import cv2
import numpy as np
import matplotlib.pyplot as plt

# 讀入灰階影像（請確認路徑存在，或自行修改）
img_path = "C:/img/sobel.bmp"
o = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
if o is None:
    raise FileNotFoundError(f"找不到圖片: {img_path}，請確認路徑或更換檔案。")

# 使用 Sobel 計算梯度（與前一題一致，採用 replicate padding）
sobelx64 = cv2.Sobel(o, cv2.CV_64F, 1, 0, ksize=3, borderType=cv2.BORDER_REPLICATE)
sobely64 = cv2.Sobel(o, cv2.CV_64F, 0, 1, ksize=3, borderType=cv2.BORDER_REPLICATE)

# 轉為 8-bit 以便顯示
sobelx = cv2.convertScaleAbs(sobelx64)
sobely = cv2.convertScaleAbs(sobely64)

# X、Y 方向加權合成
sobelxy = cv2.addWeighted(sobelx, 0.5, sobely, 0.5, 0)

# 顯示結果
plt.figure(figsize=(10, 8))
plt.subplot(2, 2, 1); plt.imshow(o, cmap='gray'); plt.title('Original'); plt.axis('off')
plt.subplot(2, 2, 2); plt.imshow(sobelx, cmap='gray'); plt.title('Sobel X'); plt.axis('off')
plt.subplot(2, 2, 3); plt.imshow(sobely, cmap='gray'); plt.title('Sobel Y'); plt.axis('off')
plt.subplot(2, 2, 4); plt.imshow(sobelxy, cmap='gray'); plt.title('Sobel X+Y'); plt.axis('off')
plt.tight_layout()
plt.show()

In [ ]:
# 練習10-3 Sobel – real case 2
import cv2
import numpy as np
import matplotlib.pyplot as plt

# 讀入灰階影像（請確認路徑存在，或自行修改）
img_path = "C:/img/lena.bmp"
o = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
if o is None:
    raise FileNotFoundError(f"找不到圖片: {img_path}，請確認路徑或更換檔案。")

# 使用 Sobel 計算梯度（與前一題一致，採用 replicate padding）
sobelx64 = cv2.Sobel(o, cv2.CV_64F, 1, 0, ksize=3, borderType=cv2.BORDER_REPLICATE)
sobely64 = cv2.Sobel(o, cv2.CV_64F, 0, 1, ksize=3, borderType=cv2.BORDER_REPLICATE)

# 轉為 8-bit 以便顯示
sobelx = cv2.convertScaleAbs(sobelx64)
sobely = cv2.convertScaleAbs(sobely64)

# X、Y 方向加權合成
sobelxy = cv2.addWeighted(sobelx, 0.5, sobely, 0.5, 0)

# 顯示結果
plt.figure(figsize=(10, 8))
plt.subplot(2, 2, 1); plt.imshow(o, cmap='gray'); plt.title('Original'); plt.axis('off')
plt.subplot(2, 2, 2); plt.imshow(sobelx, cmap='gray'); plt.title('Sobel X'); plt.axis('off')
plt.subplot(2, 2, 3); plt.imshow(sobely, cmap='gray'); plt.title('Sobel Y'); plt.axis('off')
plt.subplot(2, 2, 4); plt.imshow(sobelxy, cmap='gray'); plt.title('Sobel X+Y'); plt.axis('off')
plt.tight_layout()
plt.show()

In [7]:
# 練習 10-4
import cv2
import numpy as np

# 測試影像
image = np.array([
    [0, 1, 0, 1, 0],
    [0, 1, 1, 1, 0],
    [1, 1, 1, 1, 0],
    [0, 1, 1, 1, 1],
    [0, 0, 1, 0, 1]
], dtype=np.float32)

# Scharr 核心
Gx = np.array([
    [ 3,  0, -3],
    [10,  0,-10],
    [ 3,  0, -3]
], dtype=np.float32)

Gy = np.array([
    [ 3, 10,  3],
    [ 0,  0,  0],
    [-3,-10, -3]
], dtype=np.float32)

# BORDER_REFLECT101
padded = cv2.copyMakeBorder(image, 1, 1, 1, 1, cv2.BORDER_REFLECT101)

# 手工卷積
def convolve2d(img, kernel):
    h, w = img.shape
    k = kernel.shape[0]
    off = k // 2
    out = np.zeros((h - 2*off, w - 2*off), dtype=np.float32)

    for i in range(off, h - off):
        for j in range(off, w - off):
            region = img[i-off:i+off+1, j-off:j+off+1]
            out[i-off, j-off] = np.sum(region * kernel)
    return out

# 計算 Scharr Gx、Gy
gx = convolve2d(padded, Gx)
gy = convolve2d(padded, Gy)

# 梯度幅值（L1 版本：abs）
gradient = np.abs(gx) + np.abs(gy)

# 印出結果


print("\n=== Scharr Gradient (|Gx| + |Gy|) ===")
for r in gradient.astype(int): print(r)



=== Scharr Gradient (|Gx| + |Gy|) ===
[0 6 0 6 0]
[10 16 10 16  0]
[ 0  6  0 16 10]
[16 26  6 10  4]
[ 0 16  0  0  0]


In [ ]:
# 練習10-5 Scharr – real case
import cv2
import numpy as np
import matplotlib.pyplot as plt

# 讀入灰階影像（請確認路徑存在，或自行修改）
img_path = "C:/img/lena.bmp"
o = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
if o is None:
    raise FileNotFoundError(f"找不到圖片: {img_path}，請確認路徑或更換檔案。")

# 使用 Scharr 計算梯度（採用 replicate padding）
scharrx64 = cv2.Scharr(o, cv2.CV_64F, 1, 0)
scharry64 = cv2.Scharr(o, cv2.CV_64F, 0, 1)

# 轉為 8-bit 以便顯示
scharrx = cv2.convertScaleAbs(scharrx64)
scharry = cv2.convertScaleAbs(scharry64)

# X、Y 方向 0.5/0.5 合成（視覺化）
scharrxy = cv2.addWeighted(scharrx, 0.5, scharry, 0.5, 0)

# 顯示結果
plt.figure(figsize=(10, 8))
plt.subplot(2, 2, 1); plt.imshow(o, cmap='gray'); plt.title('Original'); plt.axis('off')
plt.subplot(2, 2, 2); plt.imshow(scharrx, cmap='gray'); plt.title('Scharr X'); plt.axis('off')
plt.subplot(2, 2, 3); plt.imshow(scharry, cmap='gray'); plt.title('Scharr Y'); plt.axis('off')
plt.subplot(2, 2, 4); plt.imshow(scharrxy, cmap='gray'); plt.title('Scharr X+Y (0.5/0.5)'); plt.axis('off')
plt.tight_layout()
plt.show()

In [11]:
# 練習10-6
import numpy as np
import cv2

# 測試影像（你可自行換成自己的 image）
image = np.array([
    [0, 1, 0, 1, 0],
    [0, 1, 1, 1, 0],
    [1, 1, 1, 1, 0],
    [0, 1, 1, 1, 1],
    [0, 0, 1, 0, 1]
], dtype=np.float32)

# Laplacian 核心（4-neighbor）
Laplacian_kernel = np.array([
    [ 0, -1,  0],
    [-1,  4, -1],
    [ 0, -1,  0]
], dtype=np.float32)


padded = cv2.copyMakeBorder(image, 1, 1, 1, 1, cv2.BORDER_REFLECT101)

# 手工卷積
def convolve2d(img, kernel):
    h, w = img.shape
    k = kernel.shape[0]
    off = k // 2
    out = np.zeros((h - 2*off, w - 2*off), dtype=np.float32)

    for i in range(off, h - off):
        for j in range(off, w - off):
            region = img[i-off:i+off+1, j-off:j+off+1]
            out[i-off, j-off] = np.sum(region * kernel)
    return out

# 計算 Laplacian（含正負號）
lap = convolve2d(padded, Laplacian_kernel)

# 取絕對值（常見於視覺化或量化突出程度）
abs_lap = np.abs(lap)

# 印出結果

print("=== |Laplacian|  ===")
for row in abs_lap.astype(int):
    print(row)


=== |Laplacian|  ===
[2 2 4 2 2]
[3 1 1 1 2]
[2 0 0 1 3]
[3 2 0 1 1]
[0 3 2 4 2]


In [ ]:
# 練習10-7 Laplacian – real case
import cv2
import numpy as np
import matplotlib.pyplot as plt

paths = [
    ("C:/img/lena.bmp", "lena.bmp"),
    ("C:/img/sobel.bmp", "sobel.bmp"),
]

for img_path, title in paths:
    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        raise FileNotFoundError(f"找不到圖片: {img_path}，請確認路徑或更換檔案。")

    # Laplacian（使用 64F 避免負值截斷，之後轉回 8-bit 顯示）
    lap64 = cv2.Laplacian(img, cv2.CV_64F, ksize=1)
    lap = cv2.convertScaleAbs(lap64)

    # 顯示
    plt.figure(figsize=(8, 4))
    plt.subplot(1, 2, 1); plt.imshow(img, cmap='gray'); plt.title(f'Original - {title}'); plt.axis('off')
    plt.subplot(1, 2, 2); plt.imshow(lap, cmap='gray'); plt.title('Laplacian (ksize=1)'); plt.axis('off')
    plt.tight_layout()
    plt.show()